// Twitter username (no @) => full canonical archive URL
export const mapping = {
	"zachleat": "https://www.zachleat.com/twitter/",
	"eleven_ty": "https://twitter.11ty.dev",
	"matthewcp": "https://matthewphillips.info/tweets/",
	"nhoizey": "https://twitter.nicolas-hoizey.com",
	"rknightuk": "https://hellsite.rknight.me",
	"steren": "https://twitter.steren.fr",
	"saneef": "https://tweets.saneef.com/",
	"accudio": "https://twitter.alistairshepherd.uk",
	"cutewitchphoebe": "https://twitter.catgirlin.space",
	"madelinecatgirl": "https://twitter.catgirlin.space",
	"purplevioletsky": "https://twitter.catgirlin.space",
	"type__error": "https://twitter.localghost.dev",
	"Chr1sHayes": "https://tweetback.hayes.software",
	"terribleMia": "https://tweets.miriamsuzanne.com",
	"iamchrisburnell": "https://twitter.chrisburnell.com",
	"overflowhidden": "https://tweets.kimjohannesen.dk",
	"lindqvistus": "https://twitter.gustavlindqvist.se",
	"sil": "https://kryogenix.org/twitter/",
	"axbom": "https://twitter.axbom.com",
	"dryan": "https://dryan.com/tweets/",
	"edwardandrews": "https://tweets.aldreth.com/",
	"lewisdaleuk": "https://twitter.lewisdale.dev",
	"ZekeAranyLucas": "https://zekearanylucas.github.io/tweets/",
	"jefflembeck": "https://twitter.jefflembeck.com"
};
